# https://cli.vuejs.org/guide/deployment.html#docker-nginx
FROM nikolaik/python-nodejs:python3.11-nodejs24 AS build-stage

COPY requirements.txt /tmp/requirements.txt
RUN pip install --root-user-action=ignore --no-cache-dir -r /tmp/requirements.txt

ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0
RUN corepack enable

WORKDIR /workdir/frontend

COPY frontend/package.json frontend/pnpm-lock.yaml frontend/pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

WORKDIR /workdir
COPY . .

ENV DJANGO_ENV=production

WORKDIR /workdir/frontend
RUN pnpm exec gettext-compile --output src/translations/translations.json locale/*/LC_MESSAGES/messages.po || true
RUN pnpm exec vue-cli-service build
WORKDIR /workdir
RUN python manage.py collectstatic --noinput -v2

FROM nginxinc/nginx-unprivileged:latest AS production-stage
USER root
COPY --from=build-stage --chown=nginx:root /workdir/frontend/dist /usr/share/nginx/html
COPY --from=build-stage --chown=nginx:root /workdir/static /usr/share/nginx/html/static
COPY --chown=nginx:root frontend/default.conf /etc/nginx/conf.d/default.conf

# Must match the settings.MEDIA_ROOT default value.
RUN mkdir -p /data/media

USER nginx
