# -*- coding: utf-8 -*-
# Generated by Django 3.1.7 on 2021-03-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlattenRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(auto_created=True, primary_key=True, serialize=False),
                ),
                ("filename", models.CharField(max_length=64)),
                ("validation_task_id", models.CharField(max_length=64)),
                ("validation_result", models.BooleanField()),
            ],
            options={
                "verbose_name": "Flatten Request",
                "verbose_name_plural": "Flatten Requests",
                "db_table": "flatten_requests",
            },
        ),
    ]
