# Generated by Django 3.1.7 on 2021-03-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_auto_20210310_1117"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flattenrequest",
            name="expired_at",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="flattenrequest",
            name="validation_result",
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name="flattenrequest",
            name="validation_task_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
