# -*- coding: utf-8 -*-
# Generated by Django 3.1.7 on 2021-03-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_auto_20210310_1121"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flattenrequest",
            name="expired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="flattenrequest",
            name="validation_result",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="flattenrequest",
            name="validation_task_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
