# -*- coding: utf-8 -*-
# Generated by Django 3.1.7 on 2021-03-10 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_auto_20210310_1125"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FlattenRequest",
            new_name="Upload",
        ),
        migrations.AlterModelOptions(
            name="upload",
            options={"verbose_name": "Upload", "verbose_name_plural": "Uploads"},
        ),
        migrations.AlterModelTable(
            name="upload",
            table="uploads",
        ),
    ]
