# Generated by Django 3.1.7 on 2021-03-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="analyzed_data_filename",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="url",
            name="analyzed_data_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="url",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued.download", "Queued download"),
                    ("analyzed_data.downloading", "Downloading analyzed data"),
                    ("downloading", "Downloading"),
                    ("queued.validation", "Queued validation"),
                    ("validation", "Validation"),
                ],
                default="queued.download",
                max_length=32,
            ),
        ),
    ]
