# Generated by Django 3.1.7 on 2021-03-18 14:11

import django.utils.timezone
from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_auto_20210317_1137"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="upload",
            name="filename",
        ),
        migrations.RemoveField(
            model_name="url",
            name="analyzed_data_filename",
        ),
        migrations.RemoveField(
            model_name="url",
            name="filename",
        ),
        migrations.AddField(
            model_name="upload",
            name="file",
            field=models.FileField(default=django.utils.timezone.now, upload_to=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="url",
            name="analyzed_data_file",
            field=models.FileField(blank=True, null=True, upload_to=core.utils.instance_directory_path),
        ),
        migrations.AddField(
            model_name="url",
            name="data_file",
            field=models.FileField(blank=True, null=True, upload_to=core.utils.instance_directory_path),
        ),
    ]
