# Generated by Django 3.1.7 on 2021-03-19 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_auto_20210319_1156"),
    ]

    operations = [
        migrations.RenameField(
            model_name="url",
            old_name="analyzed_data_file",
            new_name="analyzed_file",
        ),
    ]
