# Generated by Django 3.1.7 on 2021-03-22 14:16

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_auto_20210319_1157"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="DataSelection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tables", models.ManyToManyField(blank=True, to="core.Table")),
            ],
            options={
                "verbose_name": "Data Selection",
                "verbose_name_plural": "Data Selections",
                "db_table": "data_selections",
            },
        ),
        migrations.AddField(
            model_name="upload",
            name="selections",
            field=models.ManyToManyField(blank=True, to="core.DataSelection"),
        ),
        migrations.AddField(
            model_name="url",
            name="selections",
            field=models.ManyToManyField(blank=True, to="core.DataSelection"),
        ),
    ]
