# Generated by Django 3.1.7 on 2021-03-23 06:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_auto_20210322_1416"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="available_tables",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(default=dict), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="url",
            name="available_tables",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(default=dict), blank=True, null=True, size=None
            ),
        ),
    ]
