# Generated by Django 3.1.7 on 2021-03-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_auto_20210323_0638"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="splitted",
            field=models.BooleanField(default=False),
        ),
    ]
