# Generated by Django 3.1.7 on 2021-04-05 05:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_table_included"),
    ]

    operations = [
        migrations.RenameField(
            model_name="table",
            old_name="included",
            new_name="include",
        ),
        migrations.RenameField(
            model_name="table",
            old_name="splitted",
            new_name="split",
        ),
    ]
