# Generated by Django 3.2 on 2021-04-09 08:03

import django.contrib.postgres.fields
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_auto_20210409_0723"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="column_headings",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
