# Generated by Django 3.2 on 2021-04-15 08:22

import uuid

import django.core.files.storage
from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_table_column_headings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flatten",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "export_format",
                    models.CharField(
                        choices=[("csv", "A comma-separated values (CSV) file"), ("xlsx", "XLSX (Excel) file format")],
                        default="xlsx",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(),
                        upload_to=core.utils.instance_directory_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("processing", "PROCESSING"),
                            ("scheduled", "Scheduled"),
                        ],
                        max_length=32,
                    ),
                ),
                ("error", models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name="table",
            name="array_tables",
            field=models.ManyToManyField(blank=True, related_name="_core_table_array_tables_+", to="core.Table"),
        ),
        migrations.AddField(
            model_name="dataselection",
            name="flattens",
            field=models.ManyToManyField(blank=True, to="core.Flatten"),
        ),
    ]
