# Generated by Django 3.2 on 2021-04-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_auto_20210415_0822"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="column_headings",
        ),
        migrations.AlterField(
            model_name="flatten",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("processing", "Processing"),
                    ("scheduled", "Scheduled"),
                ],
                default="scheduled",
                max_length=32,
            ),
        ),
    ]
