# Generated by Django 3.2 on 2021-04-19 06:28

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_auto_20210416_1149"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flatten",
            name="file",
            field=models.FileField(
                blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=""
            ),
        ),
    ]
