# Generated by Django 3.2 on 2021-04-19 10:38

import django.core.files.storage
from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_alter_flatten_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flatten",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to=core.utils.export_directory_path,
            ),
        ),
    ]
