# Generated by Django 3.2 on 2021-05-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_alter_dataselection_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataselection",
            name="kind",
            field=models.CharField(
                choices=[("custom", "Custom"), ("ocds_lite", "OCDS Lite")], default="custom", max_length=10
            ),
        ),
    ]
