# Generated by Django 3.2.3 on 2021-06-23 09:14

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_auto_20210607_1429"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="analyzed_data_url",
            field=models.CharField(
                blank=True, max_length=2048, null=True, validators=[core.validators.validate_url_or_path]
            ),
        ),
        migrations.AlterField(
            model_name="url",
            name="url",
            field=models.CharField(max_length=2048, validators=[core.validators.validate_url_or_path]),
        ),
    ]
