# Generated by Django 3.2.3 on 2021-07-02 11:11

import django.contrib.postgres.fields
from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_auto_20210623_0914"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="paths",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=2048), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="url",
            name="url",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=2048, validators=[core.validators.validate_url_or_path]),
                size=None,
                validators=[core.validators.multi_upload_validator],
            ),
        ),
    ]
