# Generated by Django 3.2.3 on 2021-07-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_auto_20210623_0914"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="is_head_of_multi_upload",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="url",
            name="multi_uploads",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="_core_url_multi_uploads_+", to="core.Url"
            ),
        ),
    ]
