# Generated by Django 3.2.3 on 2021-07-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_auto_20210707_1135"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="order",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name="url",
            name="order",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
