# Generated by Django 3.2.3 on 2021-09-14 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0041_auto_20210827_0732"),
    ]

    operations = [
        migrations.RunSQL("UPDATE urls set author = NULL"),
        migrations.AlterField(
            model_name="url",
            name="author",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
