# Generated by Django 3.2.3 on 2021-09-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_alter_url_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="split",
            field=models.BooleanField(default=True),
        ),
    ]
