# Generated by Django 3.2.3 on 2021-09-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_table_mergeable"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="should_split",
            field=models.BooleanField(default=False),
        ),
    ]
