# Generated by Django 3.1.7 on 2021-03-11 13:08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spoonbill_web", "0006_auto_20210310_1259"),
    ]

    operations = [
        migrations.CreateModel(
            name="Validation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_id", models.CharField(blank=True, max_length=36, null=True)),
                ("is_valid", models.BooleanField(blank=True, null=True)),
                ("errors", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Validation",
                "verbose_name_plural": "Validations",
                "db_table": "validations",
            },
        ),
        migrations.RemoveField(
            model_name="upload",
            name="validation_result",
        ),
        migrations.RemoveField(
            model_name="upload",
            name="validation_task_id",
        ),
        migrations.AddField(
            model_name="upload",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="upload",
            name="validation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="spoonbill_web.validation",
            ),
        ),
    ]
