# Generated by Django 3.1.7 on 2021-03-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spoonbill_web", "0010_auto_20210317_1024"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="url",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued.download", "Queued download"),
                    ("analyzed_data.downloading", "Downloading analyzed data"),
                    ("downloading", "Downloading"),
                    ("queued.validation", "Queued validation"),
                    ("validation", "Validation"),
                    ("failed", "Failed"),
                ],
                default="queued.download",
                max_length=32,
            ),
        ),
    ]
