# Generated by Django 3.2 on 2021-04-08 07:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spoonbill_web", "0021_upload_analyzed_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataselection",
            name="column_headings",
            field=models.CharField(
                choices=[
                    ("ocds", "Apply OCDS headings only"),
                    ("en_user_friendly", "Apply English user friendly headings to all tables"),
                    ("en_r_friendly", "Apply English R friendly headings to all tables"),
                    ("es_user_friendly", "Apply Spanish user friendly headings to all tables"),
                    ("es_r_friendly", "Apply Spanish R friendly headings to all tables"),
                ],
                default="ocds",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="array_tables",
            field=models.ManyToManyField(
                blank=True, related_name="_core_table_array_tables_+", to="spoonbill_web.Table"
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="columns",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(default=dict), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="flatten_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
