# Generated by Django 3.2 on 2021-04-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spoonbill_web", "0022_auto_20210408_0746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="array_tables",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="_core_table_array_tables_+", to="spoonbill_web.Table"
            ),
        ),
    ]
