# Generated by Django 3.2 on 2021-04-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spoonbill_web", "0031_alter_flatten_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="analyzed_data_url",
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name="url",
            name="url",
            field=models.URLField(max_length=2048),
        ),
    ]
