# Generated by Django 3.2 on 2021-04-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spoonbill_web", "0032_auto_20210428_1147"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="heading",
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
