# Generated by Django 3.2.3 on 2021-06-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spoonbill_web", "0036_dataselection_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="country",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="url",
            name="period",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="url",
            name="source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
