# Generated by Django 4.2.15 on 2024-09-14 19:03

from django.db import migrations, models

import spoonbill_web.validators


class Migration(migrations.Migration):
    dependencies = [
        ("spoonbill_web", "0048_alter_table_array_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="heading",
            field=models.CharField(blank=True, default="", max_length=31),
        ),
        migrations.AlterField(
            model_name="table",
            name="parent",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="upload",
            name="order",
            field=models.CharField(blank=True, default="", max_length=2048),
        ),
        migrations.AlterField(
            model_name="upload",
            name="root_key",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="url",
            name="analyzed_data_url",
            field=models.CharField(
                blank=True, default="", max_length=2048, validators=[spoonbill_web.validators.validate_url_or_path]
            ),
        ),
        migrations.AlterField(
            model_name="url",
            name="country",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="url",
            name="error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="url",
            name="order",
            field=models.CharField(blank=True, default="", max_length=2048),
        ),
        migrations.AlterField(
            model_name="url",
            name="period",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="url",
            name="root_key",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="url",
            name="source",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="validation",
            name="errors",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="validation",
            name="task_id",
            field=models.CharField(blank=True, default="", max_length=36),
        ),
    ]
