from django.utils.translation import gettext_lazy as _

headings = {
    "/amendments/amendsReleaseID": _("Amendment Amended Release (identifier)"),
    "/amendments/date": _("Amendment Date"),
    "/amendments/description": _("Amendment Description"),
    "/amendments/id": _("Amendment Id"),
    "/amendments/rationale": _("Amendment Rationale"),
    "/amendments/releaseID": _("Amendment Amending Release (identifier)"),
    "/awards/contractPeriod/durationInDays": _("Contract Period Duration (days)"),
    "/awards/contractPeriod/endDate": _("Contract Period End Date"),
    "/awards/contractPeriod/maxExtentDate": _("Contract Period Maximum Extent"),
    "/awards/contractPeriod/startDate": _("Contract Period Start Date"),
    "/awards/date": _("Award Date"),
    "/awards/description": _("Award Description"),
    "/awards/id": _("Award Id"),
    "/awards/items/*/additionalClassifications/*/description": _("Classification Description"),
    "/awards/items/*/additionalClassifications/*/id": _("Classification Id"),
    "/awards/items/*/additionalClassifications/*/scheme": _("Classification Scheme"),
    "/awards/items/*/additionalClassifications/*/uri": _("Classification Uri"),
    "/awards/items/*/classification/description": _("Classification Description"),
    "/awards/items/*/classification/id": _("Classification Id"),
    "/awards/items/*/classification/scheme": _("Classification Scheme"),
    "/awards/items/*/classification/uri": _("Classification Uri"),
    "/awards/items/*/description": _("Item Description"),
    "/awards/items/*/id": _("Item Id"),
    "/awards/items/*/quantity": _("Item Quantity"),
    "/awards/items/*/unit/id": _("Unit Id"),
    "/awards/items/*/unit/name": _("Unit Name"),
    "/awards/items/*/unit/scheme": _("Unit Scheme"),
    "/awards/items/*/unit/uri": _("Unit Uri"),
    "/awards/items/*/unit/value/amount": _("Value Amount"),
    "/awards/items/*/unit/value/currency": _("Value Currency"),
    "/awards/items/additionalClassifications/description": _("Classification Description"),
    "/awards/items/additionalClassifications/id": _("Classification Id"),
    "/awards/items/additionalClassifications/scheme": _("Classification Scheme"),
    "/awards/items/additionalClassifications/uri": _("Classification Uri"),
    "/awards/items/classification/description": _("Classification Description"),
    "/awards/items/classification/id": _("Classification Id"),
    "/awards/items/classification/scheme": _("Classification Scheme"),
    "/awards/items/classification/uri": _("Classification Uri"),
    "/awards/items/description": _("Item Description"),
    "/awards/items/id": _("Item Id"),
    "/awards/items/quantity": _("Item Quantity"),
    "/awards/items/unit/id": _("Unit Id"),
    "/awards/items/unit/name": _("Unit Name"),
    "/awards/items/unit/scheme": _("Unit Scheme"),
    "/awards/items/unit/uri": _("Unit Uri"),
    "/awards/items/unit/value/amount": _("Value Amount"),
    "/awards/items/unit/value/currency": _("Value Currency"),
    "/awards/status": _("Award Status"),
    "/awards/suppliers/*/id": _("Organization Reference Id"),
    "/awards/suppliers/*/name": _("Organization Reference Name"),
    "/awards/suppliers/id": _("Organization Reference Id"),
    "/awards/suppliers/name": _("Organization Reference Name"),
    "/awards/title": _("Award Title"),
    "/awards/value/amount": _("Value Amount"),
    "/awards/value/currency": _("Value Currency"),
    "/contracts/awardID": _("Contract Award Id"),
    "/contracts/dateSigned": _("Contract Date Signed"),
    "/contracts/description": _("Contract Description"),
    "/contracts/id": _("Contract Id"),
    "/contracts/implementation/transactions/*/date": _("Transaction Information Date"),
    "/contracts/implementation/transactions/*/id": _("Transaction Information Id"),
    "/contracts/implementation/transactions/*/payee/id": _("Payee Organization Id"),
    "/contracts/implementation/transactions/*/payee/name": _("Payee Organization Name"),
    "/contracts/implementation/transactions/*/payer/id": _("Payer Organization Id"),
    "/contracts/implementation/transactions/*/payer/name": _("Payer Organization Name"),
    "/contracts/implementation/transactions/*/source": _("Transaction Information Data Source"),
    "/contracts/implementation/transactions/*/uri": _("Transaction Information Linked Spending"),
    "/contracts/implementation/transactions/*/value/amount": _("Value Amount"),
    "/contracts/implementation/transactions/*/value/currency": _("Value Currency"),
    "/contracts/implementation/transactions/date": _("Transaction Information Date"),
    "/contracts/implementation/transactions/id": _("Transaction Information Id"),
    "/contracts/implementation/transactions/payee/id": _("Payee Organization Id"),
    "/contracts/implementation/transactions/payee/name": _("Payee Organization Name"),
    "/contracts/implementation/transactions/payer/id": _("Payer Organization Id"),
    "/contracts/implementation/transactions/payer/name": _("Payer Organization Name"),
    "/contracts/implementation/transactions/source": _("Transaction Information Data Source"),
    "/contracts/implementation/transactions/uri": _("Transaction Information Linked Spending"),
    "/contracts/implementation/transactions/value/amount": _("Value Amount"),
    "/contracts/implementation/transactions/value/currency": _("Value Currency"),
    "/contracts/items/*/additionalClassifications/*/description": _("Classification Description"),
    "/contracts/items/*/additionalClassifications/*/id": _("Classification Id"),
    "/contracts/items/*/additionalClassifications/*/scheme": _("Classification Scheme"),
    "/contracts/items/*/additionalClassifications/*/uri": _("Classification Uri"),
    "/contracts/items/*/classification/description": _("Classification Description"),
    "/contracts/items/*/classification/id": _("Classification Id"),
    "/contracts/items/*/classification/scheme": _("Classification Scheme"),
    "/contracts/items/*/classification/uri": _("Classification Uri"),
    "/contracts/items/*/description": _("Item Description"),
    "/contracts/items/*/id": _("Item Id"),
    "/contracts/items/*/quantity": _("Item Quantity"),
    "/contracts/items/*/unit/id": _("Unit Id"),
    "/contracts/items/*/unit/name": _("Unit Name"),
    "/contracts/items/*/unit/scheme": _("Unit Scheme"),
    "/contracts/items/*/unit/uri": _("Unit Uri"),
    "/contracts/items/*/unit/value/amount": _("Value Amount"),
    "/contracts/items/*/unit/value/currency": _("Value Currency"),
    "/contracts/items/additionalClassifications/description": _("Classification Description"),
    "/contracts/items/additionalClassifications/id": _("Classification Id"),
    "/contracts/items/additionalClassifications/scheme": _("Classification Scheme"),
    "/contracts/items/additionalClassifications/uri": _("Classification Uri"),
    "/contracts/items/classification/description": _("Classification Description"),
    "/contracts/items/classification/id": _("Classification Id"),
    "/contracts/items/classification/scheme": _("Classification Scheme"),
    "/contracts/items/classification/uri": _("Classification Uri"),
    "/contracts/items/description": _("Item Description"),
    "/contracts/items/id": _("Item Id"),
    "/contracts/items/quantity": _("Item Quantity"),
    "/contracts/items/unit/id": _("Unit Id"),
    "/contracts/items/unit/name": _("Unit Name"),
    "/contracts/items/unit/scheme": _("Unit Scheme"),
    "/contracts/items/unit/uri": _("Unit Uri"),
    "/contracts/items/unit/value/amount": _("Value Amount"),
    "/contracts/items/unit/value/currency": _("Value Currency"),
    "/contracts/period/durationInDays": _("Period Duration (days)"),
    "/contracts/period/endDate": _("Period End Date"),
    "/contracts/period/maxExtentDate": _("Period Maximum Extent"),
    "/contracts/period/startDate": _("Period Start Date"),
    "/contracts/relatedProcesses/*/id": _("Related Process Relationship Id"),
    "/contracts/relatedProcesses/*/identifier": _("Related Process Identifier"),
    "/contracts/relatedProcesses/*/relationship/*": _("Related Process Relationship"),
    "/contracts/relatedProcesses/*/scheme": _("Related Process Scheme"),
    "/contracts/relatedProcesses/*/title": _("Related Process Title"),
    "/contracts/relatedProcesses/*/uri": _("Related Process Uri"),
    "/contracts/relatedProcesses/id": _("Related Process Relationship Id"),
    "/contracts/relatedProcesses/identifier": _("Related Process Identifier"),
    "/contracts/relatedProcesses/relationship": _("Related Process Relationship"),
    "/contracts/relatedProcesses/scheme": _("Related Process Scheme"),
    "/contracts/relatedProcesses/title": _("Related Process Title"),
    "/contracts/relatedProcesses/uri": _("Related Process Uri"),
    "/contracts/status": _("Contract Status"),
    "/contracts/title": _("Contract Title"),
    "/contracts/value/amount": _("Value Amount"),
    "/contracts/value/currency": _("Value Currency"),
    "/documents/dateModified": _("Document Date Modified"),
    "/documents/datePublished": _("Document Date Published"),
    "/documents/description": _("Document Description"),
    "/documents/documentType": _("Document Type"),
    "/documents/format": _("Document Format"),
    "/documents/id": _("Document Id"),
    "/documents/language": _("Document Language"),
    "/documents/title": _("Document Title"),
    "/documents/url": _("Document Url"),
    "/milestones/code": _("Milestone Code"),
    "/milestones/dateMet": _("Milestone Date Met"),
    "/milestones/dateModified": _("Milestone Date Modified"),
    "/milestones/description": _("Milestone Description"),
    "/milestones/dueDate": _("Milestone Due Date"),
    "/milestones/id": _("Milestone Id"),
    "/milestones/status": _("Milestone Status"),
    "/milestones/title": _("Milestone Title"),
    "/milestones/type": _("Milestone Type"),
    "/parties/additionalIdentifiers/*/id": _("Identifier Id"),
    "/parties/additionalIdentifiers/*/legalName": _("Identifier Legal Name"),
    "/parties/additionalIdentifiers/*/scheme": _("Identifier Scheme"),
    "/parties/additionalIdentifiers/*/uri": _("Identifier Uri"),
    "/parties/additionalIdentifiers/id": _("Identifier Id"),
    "/parties/additionalIdentifiers/legalName": _("Identifier Legal Name"),
    "/parties/additionalIdentifiers/scheme": _("Identifier Scheme"),
    "/parties/additionalIdentifiers/uri": _("Identifier Uri"),
    "/parties/address/countryName": _("Address Country Name"),
    "/parties/address/locality": _("Address Locality"),
    "/parties/address/postalCode": _("Address Postal Code"),
    "/parties/address/region": _("Address Region"),
    "/parties/address/streetAddress": _("Address Street"),
    "/parties/contactPoint/email": _("Contact Point Email"),
    "/parties/contactPoint/faxNumber": _("Contact Point Fax Number"),
    "/parties/contactPoint/name": _("Contact Point Name"),
    "/parties/contactPoint/telephone": _("Contact Point Telephone"),
    "/parties/contactPoint/url": _("Contact Point Url"),
    "/parties/id": _("Organization Entity Id"),
    "/parties/identifier/id": _("Primary Identifier Id"),
    "/parties/identifier/legalName": _("Primary Identifier Legal Name"),
    "/parties/identifier/scheme": _("Primary Identifier Scheme"),
    "/parties/identifier/uri": _("Primary Identifier Uri"),
    "/parties/name": _("Organization Common Name"),
    "/parties/roles": _("Organization Party Roles"),
    "/parties/roles/*": _("Organization Party Roles"),
    "/planning/budget/amount/amount": _("Amount"),
    "/planning/budget/amount/currency": _("Amount Currency"),
    "/planning/budget/description": _("Budget Source"),
    "/planning/budget/id": _("Budget Id"),
    "/planning/budget/project": _("Budget Project Title"),
    "/planning/budget/projectID": _("Budget Project Identifier"),
    "/planning/budget/uri": _("Budget Linked Information"),
    "/planning/rationale": _("Planning Rationale"),
    "/tender/additionalProcurementCategories": _("Tender Additional Procurement Categories"),
    "/tender/additionalProcurementCategories/*": _("Tender Additional Procurement Categories"),
    "/tender/awardCriteria": _("Tender Award Criteria"),
    "/tender/awardCriteriaDetails": _("Tender Award Criteria Details"),
    "/tender/awardPeriod/durationInDays": _("Evaluation And Award Period Duration (days)"),
    "/tender/awardPeriod/endDate": _("Evaluation And Award Period End Date"),
    "/tender/awardPeriod/maxExtentDate": _("Evaluation And Award Period Maximum Extent"),
    "/tender/awardPeriod/startDate": _("Evaluation And Award Period Start Date"),
    "/tender/contractPeriod/durationInDays": _("Contract Period Duration (days)"),
    "/tender/contractPeriod/endDate": _("Contract Period End Date"),
    "/tender/contractPeriod/maxExtentDate": _("Contract Period Maximum Extent"),
    "/tender/contractPeriod/startDate": _("Contract Period Start Date"),
    "/tender/description": _("Tender Description"),
    "/tender/eligibilityCriteria": _("Tender Eligibility Criteria"),
    "/tender/enquiryPeriod/durationInDays": _("Enquiry Period Duration (days)"),
    "/tender/enquiryPeriod/endDate": _("Enquiry Period End Date"),
    "/tender/enquiryPeriod/maxExtentDate": _("Enquiry Period Maximum Extent"),
    "/tender/enquiryPeriod/startDate": _("Enquiry Period Start Date"),
    "/tender/hasEnquiries": _("Tender Has Enquiries?"),
    "/tender/id": _("Tender Id"),
    "/tender/items/*/additionalClassifications/*/description": _("Classification Description"),
    "/tender/items/*/additionalClassifications/*/id": _("Classification Id"),
    "/tender/items/*/additionalClassifications/*/scheme": _("Classification Scheme"),
    "/tender/items/*/additionalClassifications/*/uri": _("Classification Uri"),
    "/tender/items/*/classification/description": _("Classification Description"),
    "/tender/items/*/classification/id": _("Classification Id"),
    "/tender/items/*/classification/scheme": _("Classification Scheme"),
    "/tender/items/*/classification/uri": _("Classification Uri"),
    "/tender/items/*/description": _("Item Description"),
    "/tender/items/*/id": _("Item Id"),
    "/tender/items/*/quantity": _("Item Quantity"),
    "/tender/items/*/unit/id": _("Unit Id"),
    "/tender/items/*/unit/name": _("Unit Name"),
    "/tender/items/*/unit/scheme": _("Unit Scheme"),
    "/tender/items/*/unit/uri": _("Unit Uri"),
    "/tender/items/*/unit/value/amount": _("Value Amount"),
    "/tender/items/*/unit/value/currency": _("Value Currency"),
    "/tender/items/additionalClassifications/description": _("Classification Description"),
    "/tender/items/additionalClassifications/id": _("Classification Id"),
    "/tender/items/additionalClassifications/scheme": _("Classification Scheme"),
    "/tender/items/additionalClassifications/uri": _("Classification Uri"),
    "/tender/items/classification/description": _("Classification Description"),
    "/tender/items/classification/id": _("Classification Id"),
    "/tender/items/classification/scheme": _("Classification Scheme"),
    "/tender/items/classification/uri": _("Classification Uri"),
    "/tender/items/description": _("Item Description"),
    "/tender/items/id": _("Item Id"),
    "/tender/items/quantity": _("Item Quantity"),
    "/tender/items/unit/id": _("Unit Id"),
    "/tender/items/unit/name": _("Unit Name"),
    "/tender/items/unit/scheme": _("Unit Scheme"),
    "/tender/items/unit/uri": _("Unit Uri"),
    "/tender/items/unit/value/amount": _("Value Amount"),
    "/tender/items/unit/value/currency": _("Value Currency"),
    "/tender/mainProcurementCategory": _("Tender Main Procurement Category"),
    "/tender/minValue/amount": _("Minimum Value Amount"),
    "/tender/minValue/currency": _("Minimum Value Currency"),
    "/tender/numberOfTenderers": _("Tender Number Of Tenderers"),
    "/tender/procurementMethod": _("Tender Procurement Method"),
    "/tender/procurementMethodDetails": _("Tender Procurement Method Details"),
    "/tender/procurementMethodRationale": _("Tender Procurement Method Rationale"),
    "/tender/procuringEntity/id": _("Procuring Entity Organization Id"),
    "/tender/procuringEntity/name": _("Procuring Entity Organization Name"),
    "/tender/status": _("Tender Status"),
    "/tender/submissionMethod": _("Tender Submission Method"),
    "/tender/submissionMethod/*": _("Tender Submission Method"),
    "/tender/submissionMethodDetails": _("Tender Submission Method Details"),
    "/tender/tenderers/*/id": _("Organization Reference Id"),
    "/tender/tenderers/*/name": _("Organization Reference Name"),
    "/tender/tenderers/id": _("Organization Reference Id"),
    "/tender/tenderers/name": _("Organization Reference Name"),
    "/tender/tenderPeriod/durationInDays": _("Tender Period Duration (days)"),
    "/tender/tenderPeriod/endDate": _("Tender Period End Date"),
    "/tender/tenderPeriod/maxExtentDate": _("Tender Period Maximum Extent"),
    "/tender/tenderPeriod/startDate": _("Tender Period Start Date"),
    "/tender/title": _("Tender Title"),
    "/tender/value/amount": _("Value Amount"),
    "/tender/value/currency": _("Value Currency"),
    "id": _("id"),
    "ocid": _("ocid"),
    "parentID": _("parentID"),
    "rowID": _("rowID"),
}
