OCDS_LITE_CONFIG = {
    "tables": {
        "awards": {
            "split": False,
            "only": (
                "/awards/date",
                "/awards/description",
                "/awards/id",
                "/awards/items/additionalClassifications",
                "/awards/items/additionalClassifications/description",
                "/awards/items/additionalClassifications/id",
                "/awards/items/additionalClassifications/scheme",
                "/awards/items/classification/description",
                "/awards/items/classification/id",
                "/awards/items/classification/scheme",
                "/awards/items/description",
                "/awards/items/id",
                "/awards/items/*/additionalClassifications",
                "/awards/items/*/additionalClassifications/*/description",
                "/awards/items/*/additionalClassifications/*/id",
                "/awards/items/*/additionalClassifications/*/scheme",
                "/awards/items/*/classification/description",
                "/awards/items/*/classification/id",
                "/awards/items/*/classification/scheme",
                "/awards/items/*/description",
                "/awards/items/*/id",
                "/awards/status",
                "/awards/suppliers/id",
                "/awards/suppliers/name",
                "/awards/suppliers/*/id",
                "/awards/suppliers/*/name",
                "/awards/title",
                "/awards/value/amount",
                "/awards/value/currency",
                "ocid",
                "id",
            ),
        },
        "contracts": {
            "split": False,
            "only": [
                "/contracts/period/durationInDays",
                "/contracts/period/endDate",
                "/contracts/period/startDate",
                "/contracts/status",
                "/contracts/title",
                "/contracts/value/amount",
                "/contracts/value/currency",
                "ocid",
                "id",
            ],
        },
        "parties": {
            "split": False,
            "only": [
                "/parties/address/countryName",
                "/parties/address/locality",
                "/parties/address/region",
                "/parties/address/streetAddress",
                "/parties/contactPoint",
                "/parties/contactPoint/email",
                "/parties/contactPoint/faxNumber",
                "/parties/contactPoint/gender",
                "/parties/contactPoint/identifier",
                "/parties/contactPoint/name",
                "/parties/contactPoint/scheme",
                "/parties/contactPoint/telephone",
                "/parties/details/branch",
                "/parties/details/BusinessOperationName",
                "/parties/details/legalEntityTypeDetail",
                "/parties/details/level",
                "/parties/details/obligada",
                "/parties/details/order",
                "/parties/details/scale",
                "/parties/details/sector",
                "/parties/identifier/id",
                "/parties/identifier/legalName",
                "/parties/identifier/scheme",
                "/parties/memberOf/id",
                "/parties/memberOf/name",
                "/parties/name",
                "/parties/roles",
                "ocid",
                "id",
            ],
        },
        "tenders": {
            "split": False,
            "only": [
                "/tender/numberOfTenderers",
                "/tender/procurementMethod",
                "/tender/procurementMethodDetails",
                "/tender/procurementMethodRationale",
                "/tender/procuringEntity",
                "/tender/procuringEntity/id",
                "/tender/procuringEntity/name",
                "/tender/status",
                "/tender/tenderers/id",
                "/tender/tenderers/name",
                "/tender/tenderers/*/id",
                "/tender/tenderers/*/name",
                "/tender/tenderPeriod/endDate",
                "/tender/tenderPeriod/startDate",
                "/tender/title",
                "/tender/value",
                "/tender/value/amount",
                "/tender/value/currency",
                "ocid",
                "id",
            ],
        },
    }
}
