name: create-docs
on:
  workflow_dispatch:
  push:
    branches:
       - master
       - main
    paths:
       - 'docs/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2.3.0
      with:
        python-version: 3.7
    - name: Install
      run: |
            pip install -r requirements_dev.txt
    - name: Build
      run: |
            cd ./docs
            make html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
        force_orphan: true
