name: pull-request-front
on:
  pull_request:
    branches:
       - master
       - main
    paths:
       - 'frontend/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      CI: true
      FILE_UPLOAD_TEMP_DIR: /tmp/
      MEDIA_ROOT: /tmp/
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3.1.0
        with:
          node-version: '10'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - run: |
              cd ./frontend
              npm install
              npm run test:unit
